@startuml
participant "Web Browser" as WebBrowser
participant "Gateway (WS/SSE)" as Gateway
participant "Message Broker" as MessageBus
box "Microservice" #LightBlue
participant "Handler" as Handler
end box

== Init ==

WebBrowser  ->>  Gateway: Send message
note right WebBrowser: ex: 'get company by id'
Gateway ->> MessageBus: Enqueue message

hnote across: "pending"

== Settled ==

alt#Gold #LightGreen Fillfill

'== Fullfill ==

MessageBus -> Handler: Consume message
activate Handler
Handler --> Handler
note over Handler: Bussiness logic here
Handler ->] : request
note right Handler: synchronous\ncall to external\nsystem 
Handler <--] : response
MessageBus <-- Handler : Enqueue message
deactivate Handler
Gateway <<- MessageBus
WebBrowser <<- Gateway

hnote across: "fulfilled"

else #Pink Reject

'== Reject ==

MessageBus -> Handler: Consume message
activate Handler
Handler --> Handler
Handler ->] : request
Handler <--] : error
Handler -> Handler: catch 
MessageBus <-- Handler : Enqueue message
deactivate Handler
Gateway <<- MessageBus
WebBrowser <<- Gateway

hnote across: "rejected"

end

@enduml